---

- hosts: server
  remote_user: root
  roles:
    - mariadb

- hosts: client
  remote_user: root
  roles:
    - sysbench

  tasks:
    - name: stop firewall service
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: (ansible_distribution == "CentOS")

    - name: stop irqbalance service
      service:
        name: irqbalance
        state: stopped
      when: (irq_bind == "on")

    - name: bind irq of ethernet card
      script: set_irq_affinity.py "{{ eth_dev }}" "{{ irq_affinity }}"
      when: (irq_bind == "on")

    - name: copy test script to client
      template:
        src: "{{ item }}"
        dest: "{{ topdir }}/{{ item }}"
      with_items:
        - sysbench-test-prepare.sh
        - sysbench-test-run.sh
        - sysbench-test-clean.sh

    - name: show sysbench-test-run hint
      debug:
        msg: "run sysbench-test-prepare.sh sysbench-test-run.sh at {{ sysbench_client }}:/{{ topdir }} dir"
      
